/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DayInstances {
  created_at: Generated<number | null>;
  id: string;
  notes: string | null;
  source_day_template_id: string | null;
}

export interface DayTemplateItems {
  day_template_id: string;
  id: string;
  practice_session_template_id: string;
  recommended_time_minutes: number | null;
  sort_order: Generated<number | null>;
}

export interface DayTemplates {
  created_at: Generated<number | null>;
  disabled_at: number | null;
  display: string;
  id: string;
}

export interface GeneratorHistory {
  day_instance_id: string | null;
  generator_id: string;
  id: string;
  picked_at: Generated<number | null>;
  value_generated: string;
}

export interface Generators {
  data_source: string | null;
  id: string;
  name: string;
  strategy: string;
}

export interface PlanningItems {
  completed_at: number | null;
  created_at: Generated<number | null>;
  display: string;
  id: string;
  min_day_instance_id: string | null;
  notes: string | null;
  was_rejected: Generated<number | null>;
}

export interface PracticeSessionInstanceGeneratedValues {
  display_value: string;
  generator_id: string | null;
  id: string;
  practice_session_instance_id: string;
  sort_order: Generated<number | null>;
}

export interface PracticeSessionInstanceLineItems {
  completed_at: number | null;
  display: string;
  id: string;
  is_completed: Generated<number | null>;
  notes: string | null;
  practice_session_instance_id: string;
  sort_order: Generated<number | null>;
  source_line_item_id: string | null;
  title: string | null;
}

export interface PracticeSessionInstances {
  actual_time_spent_minutes: Generated<number | null>;
  canceled_at: number | null;
  completed_at: number | null;
  created_at: Generated<number | null>;
  day_instance_id: string;
  display: string;
  id: string;
  notes: string | null;
  practice_session_template_id: string | null;
  recommended_time_minutes: number | null;
  sort_order: Generated<number | null>;
}

export interface PracticeSessionLineItems {
  created_at: Generated<number | null>;
  display: string;
  id: string;
  practice_session_template_id: string;
  sort_order: Generated<number | null>;
  title: string | null;
}

export interface PracticeSessionTemplateRequiredGenerators {
  generator_id: string;
  id: string;
  label: string | null;
  practice_session_template_id: string;
  quantity: Generated<number | null>;
}

export interface PracticeSessionTemplates {
  created_at: Generated<number | null>;
  default_recommended_time_minutes: Generated<number | null>;
  disabled_at: number | null;
  display: string;
  id: string;
  unique_name: string;
}

export interface SchemaMigrations {
  version: string | null;
}

export interface DB {
  day_instances: DayInstances;
  day_template_items: DayTemplateItems;
  day_templates: DayTemplates;
  generator_history: GeneratorHistory;
  generators: Generators;
  planning_items: PlanningItems;
  practice_session_instance_generated_values: PracticeSessionInstanceGeneratedValues;
  practice_session_instance_line_items: PracticeSessionInstanceLineItems;
  practice_session_instances: PracticeSessionInstances;
  practice_session_line_items: PracticeSessionLineItems;
  practice_session_template_required_generators: PracticeSessionTemplateRequiredGenerators;
  practice_session_templates: PracticeSessionTemplates;
  schema_migrations: SchemaMigrations;
}
